openapi: 3.1.0
info:
  title: My Agent API
  version: 1.0.0
paths:
  /:
    get:
      summary: Root endpoint
      operationId: root
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
